//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cslabWeb.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.AddLoginInfoSoap")]
    public interface AddLoginInfoSoap {
        
        // CODEGEN: AddInfoRequest iletisinde üst bilgi olduğundan ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        cslabWeb.ServiceReference4.AddInfoResponse AddInfo(cslabWeb.ServiceReference4.AddInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<cslabWeb.ServiceReference4.AddInfoResponse> AddInfoAsync(cslabWeb.ServiceReference4.AddInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public cslabWeb.ServiceReference4.UserDetails UserDetails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string kullaniciAdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string macAdres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string durum;
        
        public AddInfoRequest() {
        }
        
        public AddInfoRequest(cslabWeb.ServiceReference4.UserDetails UserDetails, string guid, string kullaniciAdi, string macAdres, string durum) {
            this.UserDetails = UserDetails;
            this.guid = guid;
            this.kullaniciAdi = kullaniciAdi;
            this.macAdres = macAdres;
            this.durum = durum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddInfoResult;
        
        public AddInfoResponse() {
        }
        
        public AddInfoResponse(string AddInfoResult) {
            this.AddInfoResult = AddInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddLoginInfoSoapChannel : cslabWeb.ServiceReference4.AddLoginInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddLoginInfoSoapClient : System.ServiceModel.ClientBase<cslabWeb.ServiceReference4.AddLoginInfoSoap>, cslabWeb.ServiceReference4.AddLoginInfoSoap {
        
        public AddLoginInfoSoapClient() {
        }
        
        public AddLoginInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddLoginInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddLoginInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddLoginInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cslabWeb.ServiceReference4.AddInfoResponse cslabWeb.ServiceReference4.AddLoginInfoSoap.AddInfo(cslabWeb.ServiceReference4.AddInfoRequest request) {
            return base.Channel.AddInfo(request);
        }
        
        public string AddInfo(cslabWeb.ServiceReference4.UserDetails UserDetails, string guid, string kullaniciAdi, string macAdres, string durum) {
            cslabWeb.ServiceReference4.AddInfoRequest inValue = new cslabWeb.ServiceReference4.AddInfoRequest();
            inValue.UserDetails = UserDetails;
            inValue.guid = guid;
            inValue.kullaniciAdi = kullaniciAdi;
            inValue.macAdres = macAdres;
            inValue.durum = durum;
            cslabWeb.ServiceReference4.AddInfoResponse retVal = ((cslabWeb.ServiceReference4.AddLoginInfoSoap)(this)).AddInfo(inValue);
            return retVal.AddInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cslabWeb.ServiceReference4.AddInfoResponse> cslabWeb.ServiceReference4.AddLoginInfoSoap.AddInfoAsync(cslabWeb.ServiceReference4.AddInfoRequest request) {
            return base.Channel.AddInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<cslabWeb.ServiceReference4.AddInfoResponse> AddInfoAsync(cslabWeb.ServiceReference4.UserDetails UserDetails, string guid, string kullaniciAdi, string macAdres, string durum) {
            cslabWeb.ServiceReference4.AddInfoRequest inValue = new cslabWeb.ServiceReference4.AddInfoRequest();
            inValue.UserDetails = UserDetails;
            inValue.guid = guid;
            inValue.kullaniciAdi = kullaniciAdi;
            inValue.macAdres = macAdres;
            inValue.durum = durum;
            return ((cslabWeb.ServiceReference4.AddLoginInfoSoap)(this)).AddInfoAsync(inValue);
        }
    }
}
